import React from 'react';

const Terms = () => {
    return <div className="content-wrapper">
        <h1 className='titles'>
            TERMS & CONDITIONS - OxCryptoPunks NFT Collection
        </h1>
        <p className='text-web'>
            The OxCryptoPunks NFT Collection is a series of digital artworks (NFTs) residing on the Ethereum network. 
            This platform serves as an interface exclusively for participants to engage in the exchange of digital collectibles. 
            Users bear full responsibility for the security and administration of their personal Ethereum wallets. 
            It is incumbent upon users to validate all transactions and contracts generated by this platform before granting approval. 
            Importantly, as the OxCryptoPunks smart contract operates within the Ethereum network, the reversal, undoing, or restoration of any 
            transactions is not feasible.
        </p>
        <p className='text-web'>
            This website, as well as its affiliated services, are provided on an "as is" and "as available" basis, devoid of any warranties. 
            By utilizing this website, you unreservedly assume full responsibility for all transactions concerning OxCryptoPunks digital collectibles.
        </p>
        <h1 className='titles'>
            OWNERSHIP
        </h1>
        <p className='text-web'>
            i. NFT Ownership: Each OxCryptoPunk is an NFT on the Ethereum blockchain. Upon acquiring an NFT, you acquire complete ownership of the underlying 
            OxCryptoPunk artwork. Ownership of the NFT is exclusively managed by the Smart Contract and the Ethereum network. Under no circumstances do we possess 
            the authority to seize, freeze, or alter the ownership of any OxCryptoPunk.
        </p>
        <p className='text-web'>
            ii. Personal Usage: In alignment with your ongoing adherence to these Terms, Rockstar Drop™ grants you a global, royalty-free license to employ, 
            replicate, and exhibit the procured artwork, alongside any extensions you may opt to develop or employ, solely for the subsequent purposes: (i) for 
            your personal, non-commercial use; (ii) as part of a marketplace facilitating the buying and selling of your OxCryptoPunk/NFT. 
            This necessitates cryptographic verification by the marketplace to ensure that only the legitimate owner can showcase the artwork; or (iii) within a 
            third-party website or application allowing the incorporation, engagement, or involvement of your OxCryptoPunk. This again mandates cryptographic 
            verification to guarantee that solely the genuine owner can display the artwork. Furthermore, the artwork should cease to be visible upon the 
            OxCryptoPunk owner's departure from the website/application.
        </p>
        <p className='text-web'>
            iii. Commercial Utilization: Pending your sustained adherence to these Terms, Rockstar Drop™ extends to you an unrestricted, worldwide license to exploit, 
            copy, and display the obtained artwork for the intention of creating derivative works based on the original ("Commercial Use"). Instances of such 
            Commercial Use include using the artwork to fabricate and vend merchandise such as T-shirts, bearing reproductions of the artwork. To clarify, this 
            section does not impede you from (i) possessing or managing a marketplace allowing the use and sale of OxCryptoPunks generally, provided the marketplace 
            employs cryptographic verification to confirm each owner's right to showcase the artwork; (ii) possessing or managing a third-party website or application 
            that incorporates, engages, or involves OxCryptoPunks generally, ensuring cryptographic verification of each owner's right to exhibit the artwork and its 
            subsequent invisibility once the owner departs the website/application; or (iii) gaining revenue from any of the aforementioned activities.
        </p>
    </div>;
  };
  
  export default Terms;

